### PR TITLE
Add passive tracers documentation

### PR DESCRIPTION
**Pull request by wenrongcao**
I added a md file called "readpassivetracer.md" and two associated images under /docs/src to show how to initiate tracers, perform tracer selection, and read the information back to Julia. No LaMEM source code is changed. Changes only exit in the /docs.

### CODE REVIEW

**Comment by boriskaus** [comment]
That’s great - thanks a lot.

I have two requests:
1. Can you make a link to your document [here](https://github.com/JuliaGeodynamics/LaMEM.jl/blob/2620b618ae7d5e7875ee5829b90cce20c2fa041a/docs/make.jl#L23) ? That way a link to the page will appear in the side bar
2. can you add a copy of  the full, working, script to the `examples` directory? It would allow interested users to directly run this

**Comment by wenrongcao** [comment]
Will do. For #2, I do not see `examples`. Only see `notebooks` and `scripts`. Do you want me to make a new `examples` directory?   Also, files in `notebooks` and `scripts` should be better sorted/combined if they all belong to examples.

**Comment by boriskaus** [comment]
Sorry, I meant `scripts` which is where we have the other examples as well

**Comment by boriskaus** [comment]
And feel free to better sort the scripts in those directories

**Review by boriskaus — APPROVED** [review]

**Comment by boriskaus** [comment]
since you rearranged the files in the `scripts` directory, the tests now fail (we always run these examples as part of the test to ensure that they keep working once we update the code).  Can you perhaps update the file https://github.com/JuliaGeodynamics/LaMEM.jl/blob/main/test/test_examples.jl 
and while you are at it, you can also add your new example to the test.

**Comment by wenrongcao** [comment]
Ok, I see they are connected. Will fix these tomorrow.

**Comment by wenrongcao** [comment]
The Documentation check did not pass probably due to some (local?) path information related to Subduction3D.jl not being updated.

**Comment by boriskaus** [comment]
This is the error message:
```Julia
ERROR: LoadError: Unable to generate remote link (local path does not exists)
 path: /home/runner/work/LaMEM.jl/LaMEM.jl/scripts/Subduction3D.jl
```
See [here](https://github.com/JuliaGeodynamics/LaMEM.jl/actions/runs/10676922108/job/29591252080?pr=61)

The issue is in this line:
https://github.com/JuliaGeodynamics/LaMEM.jl/blob/1c63624c55ebb12236a6695d6dacb8785fa750c0/docs/src/Subduction3D.md?plain=1#L2

**Pull request merged**
